/**
 * @file LBErrorCodes.h
 *
 * @date 9. Mai 2011
 * @author Denis Dridger
 *
 *
 * @brief This file defines commonly used error codes, 
 * which may be returned by the loadbalancing managers
 */


#ifndef LBERRORCODES_H_
#define LBERRORCODES_H_


enum LBError
{
	//MLT errors
	MLT_ERROR_INCONSISTENT_MLT,
	MLT_ERROR_CANNOT_UPDATE_MLT,
	MLT_ERROR_CANNOT_UPDATE_MLT_UNKNOWN_SERVER,
	MLT_ERROR_CANNOT_RELOAD_MLT_TO_UNDO_CHANGES,
 	MLT_ERROR_CANNOT_WRITE_TO_MLT_FILE_TO_UNDO_CHANGES,
 	MLT_ERROR_CANNOT_UNDO_MLT_CHANGES_BACKUP_DOESNT_EXIST,	
	MLT_ERROR_CANNOT_WRITE_MLT_TO_DISK,	
	MLT_ERROR_CANNOT_CREATE_NEW_ENTRY_INVALID_PATH_GIVEN,	
	MLT_ERROR_GETTING_PATH_FOR_GIVEN_INODE_FAILED,

	//communication errors
	COM_ERROR_MLT_BROADCAST_FAILED_CANNOT_SEND_REQUEST, 
	COM_ERROR_MLT_BROADCAST_FAILED_NO_REPLY_RECEIVED, 
	COM_ERROR_LOAD_REQUEST_FAILED_CANNOT_SEND_REQUEST, 
	COM_ERROR_LOAD_REQUEST_FAILED_NO_REPLY_RECEIVED, 
	
	//general load balancing errors
	LB_ERROR_NO_SERVERS_TO_CONTACT, 
	LB_ERROR_NO_BETTER_SERVER_FOUND,	
	LB_ERROR_NO_SUITABLE_NEIGHBOUR_SERVER_FOUND, 
	LB_ERROR_ANOTHER_SUBTREE_MOVE_IN_PROGRESS,
	LB_ERROR_PARTICIPANT_FAILED_TO_INTEGRATE_TREE,
	LB_ERROR_DAO_STUFF_TIMED_OUT,	

	//general file system errors
	FS_ERROR_INVALID_INODE,

	//journal errors
	JOURNAL_ERROR_UNKNOWN_INODE,
	JOURNAL_ERROR_GETTING_JOURNAL_FOR_INODE_FAILED,
	JOURNAL_ERROR_GETTING_PATH_FOR_GIVEN_INODE_FAILED,
	
	//errors coming from mds module
	MDS_ERROR_HANDLING_MIGRATION_FAILED,	
	MDS_ERROR_CANNOT_UNDO_MIGRATION,
	MDS_ERROR_GANESHA_CONFIG_UPDATE_FAILED,
	
	//storage errors	
	STORAGE_ERROR_PARTITION_NOT_FOUND,
	STORAGE_ERROR_MOUNTING_PARTITION_RO_FAILED,
	STORAGE_ERROR_MOUNTING_PARTITION_RW_FAILED,
	STORAGE_ERROR_CHANGING_INODE_OWNER_FAILED,
	STORAGE_ERROR_NO_FREE_PARTITION_AVAILABLE,
	STORAGE_ERROR_SETTING_ROOT_INODE_FAILED
};


#endif /* LBERRORCODES_H_ */
