#!/usr/bin/python
Import('config')

#make sure that the fakeClient gets compiled with the
#correct compiler
env = Environment(CC = "mpicc.openmpi")

env.Append( LIBPATH = ["../lib" ] )
env.Append( LIBS = [ "pthread", "zmq" , "fsal_shared"] )
env.Append( CCFLAGS =  config.get_cflags() )
env.Append( CPPPATH=['../include'] )

#env.Program('fakeClient', ['fakeClient.c'])
